# Generated by Django 3.1.4 on 2021-03-13 22:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurImpacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='our_impacts')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Videos', 'Videos'), ('Stories', 'Stories'), ('Activities', 'Activities')], max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
