# Generated by Django 3.1.4 on 2021-03-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourimpacts', '0002_remove_ourimpacts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourimpacts',
            name='image',
            field=models.ImageField(null=True, upload_to='our_impacts'),
        ),
    ]
